"""initial schema

Revision ID: 3a04fbb7ef3b
Revises: 
Create Date: 2026-04-26 22:04:36.663672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a04fbb7ef3b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name_enc', sa.Text(), nullable=False),
    sa.Column('phone_enc', sa.Text(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('diagnosis_type', sa.String(length=64), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_log_patient_id'), 'alert_log', ['patient_id'], unique=False)
    op.create_table('chw_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chw_actions_patient_id'), 'chw_actions', ['patient_id'], unique=False)
    op.create_table('diary_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('pain_score', sa.Integer(), nullable=False),
    sa.Column('body_temp_c', sa.Float(), nullable=True),
    sa.Column('fever_present', sa.Boolean(), nullable=False),
    sa.Column('fluid_intake_glasses', sa.Integer(), nullable=False),
    sa.Column('urine_colour', sa.Integer(), nullable=False),
    sa.Column('med_taken', sa.Boolean(), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('ambient_temp_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_tier', sa.String(length=16), nullable=True),
    sa.Column('hydration_status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diary_entries_patient_id'), 'diary_entries', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diary_entries_patient_id'), table_name='diary_entries')
    op.drop_table('diary_entries')
    op.drop_index(op.f('ix_chw_actions_patient_id'), table_name='chw_actions')
    op.drop_table('chw_actions')
    op.drop_index(op.f('ix_alert_log_patient_id'), table_name='alert_log')
    op.drop_table('alert_log')
    op.drop_table('patients')
    # ### end Alembic commands ###
