"""add User model and all core tables

Revision ID: 9fa4de292d7f
Revises: 3a04fbb7ef3b
Create Date: 2026-04-26 21:23:18.935069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fa4de292d7f'
down_revision: Union[str, None] = '3a04fbb7ef3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
